### ISSUE TITLE
Wrong pin type for SCL and SDA on the SCD30 examples

### ISSUE THREAD

**Issue by rpruizc** [knurling-rs/knurling-session-20q4#11]
The code in the SCD30 examples for declaring the SCL and SDA pins does not compile as is with the latest cargo packages. I am not completely sure if the hal version changed or not, but Twim::Pins require a floating input instead of a disconnected one.

That is:
```rust
pins.p0_30.into_floating_input().degrade();
```

Instead of:
```rust
pins.p0_30.degrade();
```

**Comment by Urhengulas** [comment]
Hi @rpruizc, Thank you for opening this issue!

I just tried compiling it locally and it actually works for me. `rust-analyzer` shows me `Pin<Input<Floating>>` as the type of both `scl` and `sda`. Adding `.into_floating_input()` still works, but doesn't seem to be needed for me.

Did you make any other changes to the code?

**Comment by Urhengulas** [comment]
I see. After running `cargo upgrade` I got the same error! 😮

**Comment by rpruizc** [comment]
Nice! Thank you Johann
