### ISSUE TITLE
Wrong circuit diagram for CA RGB LED

### ISSUE THREAD

**Issue by kellda** [knurling-rs/knurling-session-20q4#2]
The circuit diagram in https://github.com/knurling-rs/knurling-session-20q4/blob/main/src/img/knurling-rgb-led-ca-circuit.png shown a common cathode LED, and not a common anode one.

The three LEDs should be reversed for the diagram to be correct.

**Comment by Urhengulas** [comment]
Hi @kellda, Thank you for noticing this!

**Comment by Urhengulas** [comment]
@Mirabellensaft Can you please fix this or share which tool you used to create the diagram?
