### ISSUE TITLE
Wrong preparations chapter for Session 20q4?

### ISSUE THREAD

**Issue by MathiasKoch** [knurling-rs/knurling-session-20q4#26]
It seems like something has gone wrong in the book with the Preparations chapter for the CO2 sensor session here: https://github.com/knurling-rs/knurling-session-20q4/blob/main/src/sessions/Preparations.md

This looks a lot more like the shopping list for the 21q1 Minesweeper session?

**Comment by MathiasKoch** [comment]
EDIT: 
Found the actual shopping list here: https://ferrous-systems.com/blog/knurling-sessions-introduction

**Comment by Mirabellensaft** [comment]
It's indeed the wrong list, I opened a PR that fixes this.

**Comment by Urhengulas** [comment]
> It's indeed the wrong list, I opened a PR that fixes this.

Thank you!
