### ISSUE TITLE
Link to code on Github is broken

### ISSUE THREAD

**Issue by mehmetalianil** [knurling-rs/knurling-session-20q4#3]
Link such as: 

``` markdown
[3_temperature.rs](https://github.com/knurling-rs/knurling-sessions-20q4/blob/main/src/bin/3_temperature.rs).
```

in file https://github.com/knurling-rs/knurling-session-20q4/blob/main/src/sessions/internal_temp.md
are broken. I couldn't find the actual source file to correct it myself.

**Comment by Urhengulas** [comment]
Thank you @mehmetalianil. I will investigate :)

**Comment by Urhengulas** [comment]
[knurling-rs/knurling-sessions-20q4](https://github.com/knurling-rs/knurling-sessions-20q4), which contains the code examples, is currently only accessible to knurling sponsors. We will likely merge it into this repo in the next days and adapt the links accordingly.

Does this work for you @mehmetalianil?

**Comment by mehmetalianil** [comment]
> [knurling-rs/knurling-sessions-20q4](https://github.com/knurling-rs/knurling-sessions-20q4), which contains the code examples, is currently only accessible to knurling sponsors. We will likely merge it into this repo in the next days and adapt the links accordingly.
> 
> Does this work for you @mehmetalianil?

Oh, was not aware. Of course it does, just thought that it was a typo or sth.

**Comment by Urhengulas** [comment]
@mehmetalianil The links to the code examples are fixed now. Have fun!
